spring:
    profiles:
        # 从pom文件获取当前的环境develop/product/test，打包时IDEA右边Profiles根据需要勾选不同环境
        active: '@profiles.active@'
    resources:
        static-locations: 'classpath:/static'
    messages:
        # 国际化文件
        basename: i18n/messages
    session:
        store-type: redis

mybatis:
    # mybatis配置文件
    config-location: classpath:mybatis-config.xml
    # mappers文件
    mapper-locations: classpath*:/mappers/*.xml

# mybatis 分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

server:
    # 从pom文件获取当前的软件版本
    edition: '@project.version@'
    apiUrlPrefix: '/api'

logging:
  # 根据环境选择log4j2配置文件
  # mmp，log4j2启动时自动加载了一次log4j2-test.xml，环境不要命名为test为妙
  config: 'classpath:log4j2-@profiles.active@.xml'