spring:
    profiles:
        # 从pom文件获取当前的环境develop/product/test，打包时IDEA右边Profiles根据需要勾选不同环境
        active: '@profiles.active@'
    resources:
        static-locations: 'classpath:/static'
    messages:
        # 国际化文件
        basename: i18n/messages
    security:
        oauth2:
            client:
                registration:
                    github:
                        client-id: 'your client id'
                        client-secret: 'your client secret'
                        client-authentication-method: basic
                        authorization-grant-type: authorization_code
                        redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
                        scope: 'repo public_repo user'
                        client-name: 'github-client'
                provider:
                    github:
                        user-info-uri: 'https://api.github.com/user'
                        token-uri: 'https://github.com/login/oauth/access_token'
                        authorization-uri: 'https://github.com/login/oauth/authorize'
                        user-name-attribute: "email"

mybatis:
    # mybatis配置文件
    config-location: classpath:mybatis-config.xml
    # mappers文件
    mapper-locations: classpath*:/mappers/*.xml

# mybatis 分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

server:
    # 从pom文件获取当前的软件版本
    edition: '@project.version@'
    apiUrlPrefix: '/api'

logging:
    config: 'classpath:log4j2-@profiles.active@.xml'