server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/springboot_sample?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&autoReconnect=true'
    username: root
    password: 123456
  #  jms:
  #    Listener:
  #      # 默认开启消费者数量
  #      concurrency: 1
  #      # 最大消费者并行数量
  #      max-concurrency: 3
  activemq:
    broker-url: 'tcp://localhost:61616'
    user: admin
    password: admin
    # in-memory为true时，使用的是内嵌的activemq
    in-memory: false


logging:
  config: 'classpath:log4j2-develop.xml'


  
  
  
  

