server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/springboot_sample?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&autoReconnect=true'
    username: root
    password: 123456
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: '127.0.0.1'
    port: 6379
    # 当前没有设密码
    #    password:
    # 连接超时（毫秒）
    timeout: 300000
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 200
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 10
      # 连接池中的最小空闲连接
      min-idle: 0



  
  
  
  

